export interface tableData  {
    id?: number
    platform: string
    status: string
    interval: string
    activated: string
    expiry_date:string
}

export const TableDat : tableData[] = [{
    id:0,
platform:'Figma',
status: 'active',
interval: 'Monthly',
activated: 'Jan 05, 2024',
expiry_date: 'Dec 12, 2024',
},
{
    id:1,
    platform:'Dribbble',
    status: 'in',
    interval: 'Monthly',
    activated: 'Jan 05, 2024',
    expiry_date: 'Dec 12, 2024',
    },
    {
        id:2,
        platform:'Dropbox',
        status: 'Due',
        interval: 'Monthly',
        activated: 'Jan 05, 2024',
        expiry_date: 'Dec 12, 2024',
        },
        {id:3,
            platform:'Adobe',
            status: 'Due',
            interval: 'Monthly',
            activated: 'Jan 05, 2024',
            expiry_date: 'Dec 12, 2024',
            },
            {
                id:4,
                platform:'Netflix',
                status: 'active',
                interval: 'Monthly',
                activated: 'Jan 05, 2024',
                expiry_date: 'Dec 12, 2024',
                },
                {
                    id:5,
                    platform:'Spotify',
                    status: 'active',
                    interval: 'Monthly',
                    activated: 'Jan 05, 2024',
                    expiry_date: 'Dec 12, 2024',
                    },
                    {
                        id:6,
                        platform:'Chat GPT',
                        status: 'in',
                        interval: 'Monthly',
                        activated: 'Jan 05, 2024',
                        expiry_date: 'Dec 12, 2024',
                        },
                        {id:7,
                            platform:'Snapchat',
                            status: 'active',
                            interval: 'Monthly',
                            activated: 'Jan 05, 2024',
                            expiry_date: 'Dec 12, 2024',
                            },
                            {id:8,
                                platform:'Behance',
                                status: 'in',
                                interval: 'Monthly',
                                activated: 'Jan 05, 2024',
                                expiry_date: 'Dec 12, 2024',
                                },
                                {id:9,
                                    platform:'Grammarly',
                                    status: 'active',
                                    interval: 'Monthly',
                                    activated: 'Jan 05, 2024',
                                    expiry_date: 'Dec 12, 2024',
                                    },
                                    {id:10,
                                        platform:'X',
                                        status: 'in',
                                        interval: 'Monthly',
                                        activated: 'Jan 05, 2024',
                                        expiry_date: 'Dec 12, 2024',
                                        },
]